"""Mock 候选种子数据。

覆盖多城市（福州、杭州、北京）、多场景（家庭/朋友/泛化），
保证无真实 API Key 时也能输出差异化方案。
"""

# 统一维护本地 fallback 候选，方便后续按城市、场景继续扩展。
MOCK_CANDIDATE_DATA: dict[str, list[dict[str, object]]] = {
    "activity": [
        # ── 福州 ──────────────────────────────────────────
        {
            "name": "福州儿童公园",
            "tags": ["亲子", "户外", "低折腾"],
            "duration_minutes": 100,
            "area": "社区商圈",
            "price_level": "low",
            "family_friendly": True,
            "availability": "available",
            "address": "福州市台江区",
            "business_area": "台江商圈",
            "score": 8.6,
            "reason": "离市区近，有儿童游乐区，适合带娃放电。",
        },
        {
            "name": "三坊七巷文化漫步",
            "tags": ["文化", "轻松", "拍照"],
            "duration_minutes": 90,
            "area": "核心商圈",
            "price_level": "low",
            "family_friendly": True,
            "availability": "available",
            "address": "福州市鼓楼区南后街",
            "business_area": "鼓楼商圈",
            "score": 8.7,
            "reason": "福州地标，边走边看，节奏舒缓。",
        },
        {
            "name": "闽江夜游船",
            "tags": ["社交", "浪漫", "朋友局"],
            "duration_minutes": 80,
            "area": "核心商圈",
            "price_level": "medium",
            "family_friendly": False,
            "availability": "available",
            "address": "福州市台江区闽江游船码头",
            "business_area": "台江商圈",
            "score": 8.4,
            "reason": "适合朋友或情侣，夜景氛围好。",
        },
        # ── 杭州 ──────────────────────────────────────────
        {
            "name": "西湖手划船体验",
            "tags": ["亲子", "户外", "轻松"],
            "duration_minutes": 90,
            "area": "核心商圈",
            "price_level": "medium",
            "family_friendly": True,
            "availability": "available",
            "address": "杭州市西湖区北山街",
            "business_area": "西湖景区",
            "score": 9.0,
            "reason": "西湖经典体验，带孩子或朋友都合适。",
        },
        {
            "name": "杭州宋城千古情",
            "tags": ["文化", "沉浸", "社交"],
            "duration_minutes": 150,
            "area": "次核心商圈",
            "price_level": "high",
            "family_friendly": True,
            "availability": "available",
            "address": "杭州市西湖区之江路",
            "business_area": "之江板块",
            "score": 8.8,
            "reason": "大型演艺秀，朋友聚会或家庭出游都能撑场面。",
        },
        {
            "name": "龙井茶园采摘体验",
            "tags": ["亲子", "户外", "轻食"],
            "duration_minutes": 100,
            "area": "近场公园",
            "price_level": "medium",
            "family_friendly": True,
            "availability": "available",
            "address": "杭州市西湖区龙井村",
            "business_area": "龙井板块",
            "score": 8.5,
            "reason": "采茶、品茶、拍照一条龙，节奏轻松。",
        },
        {
            "name": "河坊街漫步",
            "tags": ["文化", "小吃", "轻松"],
            "duration_minutes": 70,
            "area": "核心商圈",
            "price_level": "low",
            "family_friendly": True,
            "availability": "available",
            "address": "杭州市上城区河坊街",
            "business_area": "吴山商圈",
            "score": 8.3,
            "reason": "边逛边吃，适合短时休闲。",
        },
        # ── 北京 ──────────────────────────────────────────
        {
            "name": "798艺术区",
            "tags": ["社交", "文艺", "拍照"],
            "duration_minutes": 120,
            "area": "次核心商圈",
            "price_level": "low",
            "family_friendly": False,
            "availability": "available",
            "address": "北京市朝阳区酒仙桥路",
            "business_area": "望京板块",
            "score": 8.6,
            "reason": "适合朋友拍照打卡，文艺氛围浓。",
        },
        {
            "name": "南锣鼓巷探店",
            "tags": ["社交", "小吃", "朋友局"],
            "duration_minutes": 90,
            "area": "核心商圈",
            "price_level": "low",
            "family_friendly": True,
            "availability": "available",
            "address": "北京市东城区南锣鼓巷",
            "business_area": "东城商圈",
            "score": 8.2,
            "reason": "经典胡同体验，边走边吃边聊。",
        },
        {
            "name": "奥林匹克森林公园骑行",
            "tags": ["户外", "运动", "低碳"],
            "duration_minutes": 110,
            "area": "近场公园",
            "price_level": "low",
            "family_friendly": True,
            "availability": "available",
            "address": "北京市朝阳区科荟路",
            "business_area": "奥体板块",
            "score": 8.4,
            "reason": "城市绿肺，骑行或散步都很舒服。",
        },
        # ── 通用/多城市 ────────────────────────────────────
        {
            "name": "室内亲子乐园",
            "tags": ["亲子", "室内", "低折腾"],
            "duration_minutes": 120,
            "area": "社区商圈",
            "price_level": "medium",
            "family_friendly": True,
            "availability": "available",
            "address": "社区商圈 1 号",
            "business_area": "社区商圈",
            "score": 8.9,
            "reason": "适合亲子场景，路程短，天气影响小。",
        },
        {
            "name": "社区手作体验馆",
            "tags": ["亲子", "手作", "雨天可行"],
            "duration_minutes": 100,
            "area": "社区商圈",
            "price_level": "low",
            "family_friendly": True,
            "availability": "available",
            "address": "社区商圈 18 号",
            "business_area": "社区商圈",
            "score": 8.1,
            "reason": "适合带孩子动手参与，节奏更平缓。",
        },
        {
            "name": "沉浸式剧本体验馆",
            "tags": ["社交", "互动", "朋友局"],
            "duration_minutes": 150,
            "area": "核心商圈",
            "price_level": "medium",
            "family_friendly": False,
            "availability": "available",
            "address": "核心商圈 88 号",
            "business_area": "核心商圈",
            "score": 8.5,
            "reason": "适合朋友聚会，互动感强。",
        },
        {
            "name": "保龄球社交馆",
            "tags": ["社交", "轻竞技", "朋友局"],
            "duration_minutes": 110,
            "area": "次核心商圈",
            "price_level": "medium",
            "family_friendly": False,
            "availability": "available",
            "address": "次核心商圈 33 号",
            "business_area": "次核心商圈",
            "score": 8.3,
            "reason": "上手门槛低，适合多人轻社交。",
        },
        {
            "name": "城市公园轻徒步",
            "tags": ["户外", "轻松", "低成本"],
            "duration_minutes": 90,
            "area": "近场公园",
            "price_level": "low",
            "family_friendly": True,
            "availability": "available",
            "address": "近场公园东门",
            "business_area": "近场公园",
            "score": 8.2,
            "reason": "距离近，节奏舒缓，适合短时放松。",
        },
        {
            "name": "密室逃脱挑战",
            "tags": ["社交", "互动", "烧脑"],
            "duration_minutes": 100,
            "area": "核心商圈",
            "price_level": "medium",
            "family_friendly": False,
            "availability": "available",
            "address": "核心商圈 55 号",
            "business_area": "核心商圈",
            "score": 8.4,
            "reason": "朋友聚会热门选择，协作感强。",
        },
        {
            "name": "桌游咖啡馆",
            "tags": ["社交", "聊天", "雨天可行"],
            "duration_minutes": 120,
            "area": "社区商圈",
            "price_level": "low",
            "family_friendly": False,
            "availability": "available",
            "address": "社区商圈 22 号",
            "business_area": "社区商圈",
            "score": 8.0,
            "reason": "低门槛社交场所，适合不想折腾的聚会。",
        },
    ],
    "restaurant": [
        # ── 福州 ──────────────────────────────────────────
        {
            "name": "老福州卤味馆",
            "tags": ["福州菜", "清淡可选", "出餐稳定"],
            "duration_minutes": 80,
            "area": "核心商圈",
            "price_level": "medium",
            "family_friendly": True,
            "availability": "available",
            "address": "福州市鼓楼区东街口",
            "business_area": "鼓楼商圈",
            "score": 8.6,
            "reason": "本地老字号，口味地道，适合家庭聚餐。",
        },
        {
            "name": "达明路美食街小吃",
            "tags": ["小吃", "朋友聚餐", "热闹"],
            "duration_minutes": 70,
            "area": "核心商圈",
            "price_level": "low",
            "family_friendly": True,
            "availability": "available",
            "address": "福州市鼓楼区达明路",
            "business_area": "鼓楼商圈",
            "score": 8.3,
            "reason": "福州夜宵圣地，朋友边走边吃。",
        },
        # ── 杭州 ──────────────────────────────────────────
        {
            "name": "外婆家（西湖店）",
            "tags": ["杭帮菜", "清淡可选", "朋友聚餐"],
            "duration_minutes": 80,
            "area": "核心商圈",
            "price_level": "medium",
            "family_friendly": True,
            "availability": "queue_15m",
            "address": "杭州市西湖区湖滨路",
            "business_area": "西湖景区",
            "score": 8.7,
            "reason": "杭帮菜代表，口味大众化，排队可接受。",
        },
        {
            "name": "知味观（总店）",
            "tags": ["老字号", "清淡可选", "儿童友好"],
            "duration_minutes": 75,
            "area": "核心商圈",
            "price_level": "medium",
            "family_friendly": True,
            "availability": "available",
            "address": "杭州市上城区仁和路",
            "business_area": "吴山商圈",
            "score": 8.5,
            "reason": "百年老字号，小笼包和猫耳朵必点。",
        },
        # ── 北京 ──────────────────────────────────────────
        {
            "name": "海底捞（朝阳店）",
            "tags": ["火锅", "朋友聚餐", "服务好"],
            "duration_minutes": 100,
            "area": "次核心商圈",
            "price_level": "high",
            "family_friendly": True,
            "availability": "queue_20m",
            "address": "北京市朝阳区三里屯",
            "business_area": "三里屯商圈",
            "score": 8.8,
            "reason": "朋友聚会首选火锅，服务体验拉满。",
        },
        {
            "name": "四季民福烤鸭店",
            "tags": ["烤鸭", "北京特色", "朋友聚餐"],
            "duration_minutes": 90,
            "area": "核心商圈",
            "price_level": "medium",
            "family_friendly": True,
            "availability": "available",
            "address": "北京市东城区南池子大街",
            "business_area": "东城商圈",
            "score": 8.9,
            "reason": "本地人推荐的烤鸭店，比全聚德性价比高。",
        },
        # ── 通用 ──────────────────────────────────────────
        {
            "name": "家常菜亲子餐厅",
            "tags": ["亲子座椅", "家常菜", "清淡可选"],
            "duration_minutes": 90,
            "area": "社区商圈",
            "price_level": "medium",
            "family_friendly": True,
            "availability": "queue_15m",
            "address": "社区商圈 5 号",
            "business_area": "社区商圈",
            "score": 8.8,
            "reason": "适合家庭聚餐，排队时间可接受。",
        },
        {
            "name": "热闹烤肉店",
            "tags": ["朋友聚餐", "气氛好"],
            "duration_minutes": 100,
            "area": "核心商圈",
            "price_level": "medium",
            "family_friendly": False,
            "availability": "available",
            "address": "核心商圈 29 号",
            "business_area": "核心商圈",
            "score": 8.7,
            "reason": "适合多人朋友场景，执行成功率高。",
        },
        {
            "name": "轻食简餐吧",
            "tags": ["轻食", "快捷", "少负担"],
            "duration_minutes": 70,
            "area": "近场公园",
            "price_level": "low",
            "family_friendly": True,
            "availability": "available",
            "address": "近场公园南侧",
            "business_area": "近场公园",
            "score": 8.0,
            "reason": "适合清淡偏好，衔接顺畅。",
        },
        {
            "name": "港式茶餐厅",
            "tags": ["出餐稳定", "朋友聚餐", "儿童友好"],
            "duration_minutes": 80,
            "area": "社区商圈",
            "price_level": "medium",
            "family_friendly": True,
            "availability": "available",
            "address": "社区商圈 12 号",
            "business_area": "社区商圈",
            "score": 8.4,
            "reason": "上菜稳定、口味覆盖广，适合作为稳妥餐饮备选。",
        },
        {
            "name": "川味小馆",
            "tags": ["重口味", "朋友聚餐", "下饭"],
            "duration_minutes": 85,
            "area": "次核心商圈",
            "price_level": "low",
            "family_friendly": False,
            "availability": "available",
            "address": "次核心商圈 16 号",
            "business_area": "次核心商圈",
            "score": 7.9,
            "reason": "适合偏重口味的朋友聚餐，但不适合清淡需求。",
        },
        {
            "name": "日式简餐定食屋",
            "tags": ["清淡可选", "快捷", "一人食"],
            "duration_minutes": 60,
            "area": "核心商圈",
            "price_level": "medium",
            "family_friendly": True,
            "availability": "available",
            "address": "核心商圈 40 号",
            "business_area": "核心商圈",
            "score": 8.1,
            "reason": "出餐快、口味清淡，适合时间紧凑的安排。",
        },
        {
            "name": "素食养生餐厅",
            "tags": ["清淡可选", "健康", "安静"],
            "duration_minutes": 70,
            "area": "社区商圈",
            "price_level": "medium",
            "family_friendly": True,
            "availability": "available",
            "address": "社区商圈 8 号",
            "business_area": "社区商圈",
            "score": 7.8,
            "reason": "全素食，适合注重健康或清淡饮食的家庭。",
        },
        {
            "name": "烧烤大排档",
            "tags": ["重口味", "朋友聚餐", "热闹"],
            "duration_minutes": 95,
            "area": "次核心商圈",
            "price_level": "low",
            "family_friendly": False,
            "availability": "available",
            "address": "次核心商圈 28 号",
            "business_area": "次核心商圈",
            "score": 8.0,
            "reason": "朋友聚会经典选择，氛围感强。",
        },
    ],
    "addon": [
        # ── 福州 ──────────────────────────────────────────
        {
            "name": "闽江边散步看夜景",
            "tags": ["轻松", "散步", "浪漫"],
            "duration_minutes": 40,
            "area": "核心商圈",
            "price_level": "low",
            "family_friendly": True,
            "availability": "available",
            "address": "福州市台江区闽江沿岸",
            "business_area": "台江商圈",
            "score": 8.0,
            "reason": "餐后沿江散步，节奏轻松。",
        },
        # ── 杭州 ──────────────────────────────────────────
        {
            "name": "西湖音乐喷泉",
            "tags": ["免费", "浪漫", "收尾"],
            "duration_minutes": 30,
            "area": "核心商圈",
            "price_level": "low",
            "family_friendly": True,
            "availability": "available",
            "address": "杭州市西湖区湖滨",
            "business_area": "西湖景区",
            "score": 8.2,
            "reason": "免费观赏，适合作为行程收尾。",
        },
        # ── 北京 ──────────────────────────────────────────
        {
            "name": "后海酒吧街散步",
            "tags": ["社交", "夜生活", "朋友局"],
            "duration_minutes": 60,
            "area": "核心商圈",
            "price_level": "medium",
            "family_friendly": False,
            "availability": "available",
            "address": "北京市西城区后海",
            "business_area": "什刹海商圈",
            "score": 8.1,
            "reason": "朋友聚会收尾经典去处，氛围好。",
        },
        # ── 通用 ──────────────────────────────────────────
        {
            "name": "甜品补给站",
            "tags": ["收尾", "轻社交"],
            "duration_minutes": 45,
            "area": "同商圈",
            "price_level": "low",
            "family_friendly": True,
            "availability": "available",
            "address": "同商圈 A1",
            "business_area": "同商圈",
            "score": 7.8,
            "reason": "作为收尾补充，保持 4-6 小时完整闭环。",
        },
        {
            "name": "河边散步收尾",
            "tags": ["轻松", "散步", "低成本"],
            "duration_minutes": 40,
            "area": "近场公园",
            "price_level": "low",
            "family_friendly": True,
            "availability": "available",
            "address": "近场公园沿河步道",
            "business_area": "近场公园",
            "score": 7.7,
            "reason": "餐后轻松散步，适合少折腾场景。",
        },
        {
            "name": "桌游放松局",
            "tags": ["社交", "聊天", "雨天可行"],
            "duration_minutes": 60,
            "area": "核心商圈",
            "price_level": "medium",
            "family_friendly": False,
            "availability": "available",
            "address": "核心商圈 61 号",
            "business_area": "核心商圈",
            "score": 7.9,
            "reason": "适合朋友场景的低门槛续摊。",
        },
        {
            "name": "奶茶店小坐",
            "tags": ["轻松", "聊天", "低成本"],
            "duration_minutes": 35,
            "area": "社区商圈",
            "price_level": "low",
            "family_friendly": True,
            "availability": "available",
            "address": "社区商圈 B3",
            "business_area": "社区商圈",
            "score": 7.5,
            "reason": "最轻量的收尾选择，随时可以结束。",
        },
        {
            "name": "电影院看场电影",
            "tags": ["室内", "雨天可行", "收尾"],
            "duration_minutes": 120,
            "area": "核心商圈",
            "price_level": "medium",
            "family_friendly": True,
            "availability": "available",
            "address": "核心商圈 77 号",
            "business_area": "核心商圈",
            "score": 7.6,
            "reason": "如果时间充裕，看电影是万能收尾。",
        },
    ],
}
